### ISSUE TITLE
Is it worth storing hardcoded SQL (currently in R) as separate SQL files?

### ISSUE THREAD

**Issue by kzollove** [OHDSI/GIS#148]
Some of these SQL snippets are small, but some are growing larger (but still only around 10-20 lines). Is there any sort of advantage to pulling these SQL snippets into external SQL scripts, then reading into R for execution?

@rtmill thoughts?

**Comment by rtmill** [comment]
Not sure matters too much at the moment, but I can see it becoming a more viable solution if the number of queries gets large. 

If we went the SQL route we would want to build the execution function with SQLRender around it as I would guess some will be parameterized
