### ISSUE TITLE
loadGeometry fails to transform geom_local_value when source is character

### ISSUE THREAD

**Issue by kzollove** [OHDSI/GIS#195]
![image](https://github.com/OHDSI/GIS/assets/18039765/24efca9d-fe4e-413c-903a-d69cdab8c5df)

This issue manifests as unable to transform source to wgs84, but after a little digging, it forces another issue: how to handle source data that contains multiple CRS.

Solution for multiple CRS: break into distinct DFs by CRS, transform to wgs84, then recombine.

When should this CRS step occur? Probably before the main error in this issue is ever encountered... A bit of a chicken or egg situation.

**Comment by tibbben** [comment]
Just need to force geom type on column, sometimes the geom column comes in as archer (not geom) during ETL.

**Comment by kzollove** [comment]
This was related to a data_source that isn't in the main catalog, but should be.

Once #255 and #256 are closed, try this again (101 in the example picture refers to aqs_sites from #255)

**Comment by kzollove** [comment]
Not sure if this is the exact same bug, but this can seemingly be reproduced with:

![image](https://github.com/OHDSI/GIS/assets/18039765/96e384fa-8b8c-4199-8b88-89c56c5f1824)

**Comment by kzollove** [comment]
Not sure if this is still a thing, would like to see if it can be reproduced.

If so address immediately.
