### ISSUE TITLE
Explore SDoHO 

### ISSUE THREAD

**Issue by kzollove** [OHDSI/GIS#211]
Download link on this page https://sbmi.uth.edu/bsdi/project.htm

**Comment by p-talapova** [comment]
The SDoHO ontology (OWL) was transformed into a tabular format with preserved hierarchy and incorporated into the SDOH OMOP vocabulary in the OMOP pre-stage format (see attached).

[sdoho_prestage.csv](https://github.com/OHDSI/GIS/files/12407922/sdoho_prestage.csv)

**Comment by kzollove** [comment]
Committed to main in [cb150be](https://github.com/OHDSI/GIS/commit/cb150be022aa664f5bd85f89044d0fa73167acc5)
