### ISSUE TITLE
Add SDoHO Ontology

### ISSUE THREAD

**Issue by kzollove** [OHDSI/GIS#216]
SDoHO available from [this](https://sbmi.uth.edu/bsdi/files/SDoHO_June2023.zip?language_id=1) download link

**Comment by kzollove** [comment]
The 2018 ACS Social Vulnerability Index variable EP_POV has the description "Percentage of persons below poverty estimate"

This would be a good candidate variable to transcribe to SDoHO

**Comment by kzollove** [comment]
[Download link](https://sbmi.uth.edu/bsdi/files/SDoHO_June2023.zip?language_id=1) for SDoHO owl files

**Comment by p-talapova** [comment]
The SDoHO ontology (OWL) was transformed into a tabular format with preserved hierarchy and incorporated into the SDOH OMOP vocabulary in the OMOP pre-stage format (see attached).

[sdoho_prestage.csv](https://github.com/OHDSI/GIS/files/12407922/sdoho_prestage.csv)
