### ISSUE TITLE
Vocabulary needs for OHDSI Symposium

### ISSUE THREAD

**Issue by kzollove** [OHDSI/GIS#223]
- [x] #224 
- [x] #230 
- [x] #225 
- [ ] #245
- [x] #226 
- [ ] #227 
- [ ] #228 
- [ ] #229

**Comment by kzollove** [comment]
9/15/23 Polina update
First run of sdoho completed (with some minor errors)
Same with Toxin Toxin 
Will be completed soon
Added geography terms
Where to store vocabulary documentation?

**Comment by kzollove** [comment]
@p-talapova The new concept_class "Geometry Relationship" [here](https://github.com/OHDSI/GIS/blob/vocabulary_work/vocabularies/gis_vocabs_concept_stage_v1.tsv) is one character too long for the concept.concept_class field per the [CDM v5.4 DDL constraints](https://ohdsi.github.io/CommonDataModel/cdm54.html#CONCEPT)

![image](https://github.com/OHDSI/GIS/assets/18039765/ea6f44d7-1665-4513-809b-051eafc23328)


Should we change to 'Geom Relationship'? For my temporary work I am changing to GeometryRelationship

**Comment by p-talapova** [comment]
@kzollove thanks for pointing that out! Let me revisit the issue. 
I will update the branch by the end of the week, incorporating documentation, scripts, and improved staging tables (the more findings, the better).

One way to handle this situation is by utilizing the concept_synonym table, which allows us to associate longer concept names with shorter versions. Additionally, we should apply abbreviated versions of concept classes where needed.

But for the preliminary test run, I employed a temporary solution:
```
ALTER TABLE concept_manual
ALTER COLUMN concept_name TYPE varchar;
ALTER TABLE concept_manual
ALTER COLUMN concept_class_id TYPE varchar;
```

**Comment by p-talapova** [comment]
> @p-talapova The new concept_class "Geometry Relationship" [here](https://github.com/OHDSI/GIS/blob/vocabulary_work/vocabularies/gis_vocabs_concept_stage_v1.tsv) is one character too long for the concept.concept_class field per the [CDM v5.4 DDL constraints](https://ohdsi.github.io/CommonDataModel/cdm54.html#CONCEPT)
> 
> ![image](https://user-images.githubusercontent.com/18039765/272027632-ea6f44d7-1665-4513-809b-051eafc23328.png)
> 
> Should we change to 'Geom Relationship'? For my temporary work I am changing to GeometryRelationship

I encourage you to feel free to customize or highlight anything that may not align with OMOP rules or your preferences. Afterward, we can have a discussion about the results and work together to define the necessary actions.

**Comment by p-talapova** [comment]
> Where to store vocabulary documentation?

I would like to create documentation directly within [the branch](https://github.com/OHDSI/GIS/tree/vocabulary_work), hopefully by tomorrow.
