### ISSUE TITLE
Define source terms that need mapping

### ISSUE THREAD

**Issue by kzollove** [OHDSI/GIS#224]
Define source terms that are relevant to the SDoH and pollutant use cases to be demonstrated at the OHDSI Symposium (October 2023)

Examples from every source field to be mapped will help to clarify the full scope of vocabulary/hierarchy development

- [x] source terms for SDoH use case
- [x] source terms for pollutant use case

**Comment by rtmill** [comment]
Content for SVI 2020 concepts attached

**Comment by rtmill** [comment]
Content for CDC AQS concepts:
[CDC_AQS_codes.csv](https://github.com/OHDSI/GIS/files/12374029/CDC_AQS_codes.csv)

From: https://aqs.epa.gov/aqsweb/documents/codetables/methods_all.html

**Comment by rtmill** [comment]
Two content sources provided above
