### ISSUE TITLE
Prepare to collect emails of interested contributors

### ISSUE THREAD

**Issue by kzollove** [OHDSI/GIS#232]
(edit sep 8 2023, after WG discussion): Instead of picking an arbitrary future date for a hackathon, we should reframe the sign-up sheet to collect emails from potential collaborators with a general interest in participating in a hackathon or tutorial that would cover XYZ topics.

- [ ] Are you interested in learning more? Contributing to development? Contributing to data source curation? Joing the OHDSI GIS WG? 
- [ ] What are the potential hackathon topics?
- [ ] What are the potential tutorial/walkthrough topics?
- [ ] Create google form to allow sign ups at symposium

**Comment by kzollove** [comment]
Is the purpose of this hackathon for creating new data/ variable sources? If yes, good to do a serious inventory of what type of data sources gaia currently supports beforehand. Setting expectations correctly so we don't have an hour long session telling people their data source is too complex

**Comment by tibbben** [comment]
good question. Perhaps enumerating the purpose(s) would be good:

1. help people stand up the stack - walk them through it
2. show people how to load existing data sources in the catalog
3. create data sources (as noted by Kyle)
4. others ....

**Comment by tibbben** [comment]
If the above list looks like it is complete, I will write up a short paragraph and set some dates ....

**Comment by kzollove** [comment]
Thanks for starting the list of foci for the hackathon @tibbben! I think this would be a good thing to go over with the group at a weekly meeting. 

If we expand the topics covered in the hackathon we should remember to appropriately advertise the limitations ahead of time to avoid dragging down the session

**Comment by kzollove** [comment]
## Potential hackathon topics:
- Creating/minting data sources and variable sources
- Unit testing, documentation :) 

## Potential tutorial topics:
- Install and set up
- Creating/minting data sources
- geocoding
- Running using gaiaCore
- "Layer" creation (once we figure it out)
