### ISSUE TITLE
databaseSchema not created for loadVariable

### ISSUE THREAD

**Issue by tibbben** [OHDSI/GIS#234]
```
gaiaCore::loadVariable(connectionDetails,75)
Connecting using PostgreSQL driver
Connecting using PostgreSQL driver
Connecting using PostgreSQL driver
Connecting using PostgreSQL driver
Error in gaiaCore::loadVariable(connectionDetails, 75) : 
  1 assertions failed:
 * Variable 'databaseSchema': Must have length 1, but has length 0
```
It seems that the schema to hold the actual data was not created in a blank instance. Code run before this:
```
library(gaiaCore)

# must download driver first, see: https://ohdsi.github.io/DatabaseConnectorJars/
Sys.setenv("DATABASECONNECTOR_JAR_FOLDER" = "d:/Sync/gitRepos/GIS/dbJars")

# set database connection
connectionDetails <- DatabaseConnector::createConnectionDetails(
## the details ##
) 

# initialize DB connection
gaiaCore::initializeDatabase(connectionDetails) 
```

**Comment by kzollove** [comment]
Thanks for reporting this bug @tibbben.

I plan to do a top-to-bottom run through of gaiaCore early next week. I'll try to make sure that all issues, including this, are sorted at that point.

The goal at that point will be that the **loadVariable()** function supports all data sources that we have "published".

**Comment by kzollove** [comment]
> ok - so I have figured this out a little more, you must first run: `gaiaCore::createIndices(connectionDetails)` 

I am trying to remember if there was any reason that this wasn't originally baked in to the intializeDatabase function... it would need to be run when new data sources or variable sources were created, but for most users that is not often. I think I am going to add it in initializeDatabase (after addressing the bugs you discovered running createIndices)

**Comment by tibbben** [comment]
yep, perhaps include createIndices() in the into routine?

**Comment by kzollove** [comment]
On second look, createIndices() was already part of the initializeDatabase() function.

Now that createIndices() is working, I think that this issue can be closed.

@tibbben. can you please run `gaiaCore::initializeDatabase(connectionDetails, overwrite = TRUE)` and enter `2` to rebuild the backbone schema? attr_index table should have 30 entries and geom_index should have 121

If that fixes this issue, please close it after. Thanks again for submitting the bug!
