### ISSUE TITLE
createIndices fails; does not populate index tables

### ISSUE THREAD

**Issue by kzollove** [OHDSI/GIS#236]
@tibbben first identified this issue in #234 

createIndices(), which should be run immediately after initializeDatabase as part of the install process, does not add any records to the two index tables (attr_, geom_)

The root of this problem occurs when the functions getDataSourceTable and getVariableSourcetable are called, which subsequently call the DatabaseConnector function dbReadTable, which returns column names in uppercase:
https://github.com/OHDSI/GIS/blob/b7733fae3c1b1e5c2ea42fe581c5bf450ea7b183/R/dbUtils.R#L195
https://github.com/OHDSI/GIS/blob/b7733fae3c1b1e5c2ea42fe581c5bf450ea7b183/R/dbUtils.R#L211

It seems the simplest fix is to change the column names to lower case in the R tables that are returned from getDataSourceTable and getVariableSourcetable

**Comment by tibbben** [comment]
agreed - but I am curious as to the thinking behind that behavior to capitalize everything in databaseConnector. Are we missing something? Also this solution may cause some havoc with source tables that have mixed case column headers .. I am also grappling with these issues in GDSC. Note that ogr2ogr converts everything to lower.

In any case, for October, I think the best is to simply convert the labels back to lower as you suggest.

I am also encountering problems with columns that start with a number or have spaces .... just a heads up.

**Comment by kzollove** [comment]
Thanks for the feedback.

I cant understand _why_ the databaseconnector function returns capitalized column headers after a very quick check, but I agree, It'd be good to better understand that choice. 

> Also this solution may cause some havoc with source tables that have mixed case column headers

> I am also encountering problems with columns that start with a number or have spaces

I don't think anything currently in the gaia catalog has spaces, mixed case column headers, or starts with numbers. I don't know if we should ever allow/support that...

**Comment by kzollove** [comment]
True, we will need to support tons of weird stuff coming out of data sources, but as far as our own schemas go we should avoid
