### ISSUE TITLE
old package reference? 

### ISSUE THREAD

**Issue by rtmill** [OHDSI/GIS#248]
References "GIS" instead of "gaiaCore", blew up

https://github.com/OHDSI/GIS/blob/dd5f6806e6c1f7ebf8889aec4d941ca3afcb911f/R/dbUtils.R#L164

**Comment by kzollove** [comment]
Nice find @rtmill ! I'll put in a fix ASAP.

Did changing to gaiaCore solve the problem for you? For some reason this hasn't caused anything to blow up on my end. I think same with Tim.
