### ISSUE TITLE
Create Use Case Process and Guidance

### ISSUE THREAD

**Issue by kzollove** [OHDSI/GIS#300]
- [ ] #301
 - [ ] Set up regular coordinating  for Use Case owners

**Comment by kzollove** [comment]
I've created a Use Case issue template, revised after feedback from the group, and started a process document to outline how a new use case proposal process would look.

**Comment by kzollove** [comment]
For use case issue template: RACI chart for listing use case project's team members and assigning accountability

**Comment by martyalvarez** [comment]
I looked up RACI charts and mocked up a bare bones draft of one – mostly for my internal purposes.
Once we have a use case that may benefit from one, I’m happy to work with the lead/team to complete a first pass!
