### ISSUE TITLE
Planning for meeting with Patrick Florance (Director of Research Technology at Tufts University, GeoData at Tufts)

### ISSUE THREAD

**Issue by kzollove** [OHDSI/GIS#302]
Director of Research Technology at Tufts University

Tufts GeoPortal "GeoData at Tufts"

- Do we help develop work on GeoPortal (contributions to GH haven't been made in awhile, but software continues to function)
- What do we want to do to understand the potential value of GeoPortal? With our current resources, but also if we were able to acquire more (time, staffing)
- Is there an easy way to "crosswalk" between their existing datasets and our catalog? Crosswalk into DCAT/schema.org?
- Standing up new instance of GeoPortal, or carving out a section of GeoData at Tufts for "Health Analytics with OHDSI"?
- What metadata elements are they using? What do they find useful? What custom metadata elements are they using?
- GeoData does not have variable level metadata, though they do have tools for linking variables
- How is metadata for versioning handled?
- [GeoBlacklight ](https://geoblacklight.org/)- community project driven by Stanford
- OpenGeoPortal metadata standard
- How is metadata federated?

Marty added from 1/12/24 GIS meeting:
- What was their strategy to federate metadata within partner organizations? (Tim)
- What is your strategy to expose metadata to search engines and indexers? (Tim)
- How have they managed the tension of having custom internal metadata? (Tim)

Marty added from 1/19/24 GIS meeting:
- What is their process to ingest new data? (Tim)
- What is the potential of incorporating the GIS Vocabulary package into the Athena package? What does the community think about the opportunities to browse, manage, and expand mappings and Vocabularies outside of Athena in a more function-rich environment, given that Athena does not support real-time edit submissions or updates? (Tim)

**Comment by martyalvarez** [comment]
Initial email was sent to Patrick. Waiting for response.

**Comment by kzollove** [comment]
TODO:
- [ ] Report on size of lift for leveraging existing GeoData metadata
- [ ] Report on strategies for federated metadata sharing

**Comment by martyalvarez** [comment]
Meeting with Patrick Florance about GeoData and OHDSI/Tufts is scheduled for Friday, Jan 26, 2024
