### ISSUE TITLE
[DOCUMENTATION] How To Install?

### ISSUE THREAD

**Issue by TheCedarPrince** [OHDSI/GIS#308]
I was curious about how to set-up and install GaiaDB but the instructions like here: https://ohdsi.github.io/GIS/geocodingFull.html#Connect_to_gaiaDB_server leads to a dead end. How do I set-up and install the database? 

Thanks!

~ tcp :deciduous_tree:

**Comment by kzollove** [comment]
HI @TheCedarPrince ! Thanks for reporting this. We've been rebuilding the docs and this was clearly an oversight... I'll get this fixed by the end of next week

**Comment by TheCedarPrince** [comment]
You the bomb dot com @kzollove ! Also, happy holidays! Hope you are staying warm! :christmas_tree: :santa: :coffee:

**Comment by kzollove** [comment]
@TheCedarPrince thanks again for reporting this! The docs website should now be updated [here](https://ohdsi.github.io/GIS/get-started.html).

Sorry for the delay and let me know if anything remains unclear

**Comment by TheCedarPrince** [comment]
Glorious @kzollove ! I shall try this out very soon and will report back any issues I run into! Thanks!!!
