### ISSUE TITLE
[2024 Symposium] Data Catalog

### ISSUE THREAD

**Issue by kzollove** [OHDSI/GIS#346]
Items to be completed in support of Data Catalog in advance of the OHDSI Symposium

 - Demonstrate how to find, configure, and load PM2.5 data into the GIS backbone
 - Show catalog functionality for registering new data sources
 - Prepare documentation/demonstration of the process

## TODO:
- [ ] #351

**Comment by jaygee-on-github** [comment]
@tibbben, @kzollove, @fils, @AEW0330, @martyalvarez -- We didn't meet this week. We are scheduled to meet Monday or Tuesday of next week at a time when Kyle is able to join. That being said, we tentatively (by way of osmosis) put together [our learning objectives](https://github.com/OHDSI/GIS/issues/351) for review/discussion in our meeting next week

**Comment by kzollove** [comment]
Doug has been looking at how to merge GDSC work with the OHDSI GIS schema

**Comment by kzollove** [comment]
Are we situated to bring the OpenGeoPortal resources into our own Data Catalog? Would that work through the pipeline that Data Catalog team has been developing?

**Comment by jaygee-on-github** [comment]
Kyle 

Can you provide a link to these resources so I can look at this more carefully with Doug and Tim?

Thanks.

Sorry about today.

We did have a good meeting though,


Jay

On Sep 6, 2024, at 10:50 AM, Kyle Zollo ***@***.***> wrote:


Are we situated to bring the OpenGeoPortal resources into our own Data Catalog? Would that work through the pipeline that Data Catalog team has been developing?

**Comment by kzollove** [comment]
@jaygee-on-github 

> Can you provide a link to these resources so I can look at this more carefully with Doug and Tim?

I can direct you to https://opengeoportal.io/ and https://geoblacklight.org/, but I believe @tibbben might be able to direct you to the more relevant links within those sites

**Comment by kzollove** [comment]
We need to ensure that the data sources are represented identically in the GDSC data catalog and gaia-db @tibbben @kzollove 

- [ ] What fields need to be added to gaia-db
- [ ] Which data_sources/variable_sources (subset of the SEDACS dataset) need to be added to gaia-db and GDSC?

**Comment by jaygee-on-github** [comment]
Can we table this somehow and actually use the table in the code?GDSC could be a superset and there may be different namesSent from my iPhoneJay Greenfield202.271.3179On Sep 27, 2024, at 10:59 AM, Kyle Zollo ***@***.***> wrote:﻿
We need to ensure that the data sources are represented identically in the GDSC data catalog and gaia-db @tibbben @kzollove

 What fields need to be added to gaia-db
 Which data_sources/variable_sources (subset of the SEDACS dataset) need to be added to gaia-db and GDSC?
