### ISSUE TITLE
Define OHDSI symposium workshop learning objectives for Data Catalog

### ISSUE THREAD

**Issue by kzollove** [OHDSI/GIS#351]
## Catalog learning objectives
- How to identify relevant datasets from literature in your field; when to fall back on OHDSI GIS group for assistance
- get catalog entry in to spreadsheet (database?) (include variables in catalog??) | minimum required ...
- search catalog and add specific variables to ETL process
- share metadata with other research groups?

**Comment by jaygee-on-github** [comment]
- Determine what parts of a [CreativeWork](https://schema.org/CreativeWork) and/or other schemas in schema.org JSON-LD form the target metadata for the catalog entries 
- Determine how we will load the schema.org JSON.LD catalog entries into the GIS backbone
- Decide on a standard input format for the schema.org JSON-LD catalog entries
- Provide step by step directions for building a mapping table that moves standard input into the schema.org JSON-LD
- Decide on a shape for the schema.org JSON-LD knowledge graph that captures all the catalog entries
- Provide step by step instructions for navigating and/or querying this knowledge graph
- Capture this step by step in a YouTube

**Comment by tibbben** [comment]
> [Jay](@jaygee-on-github), this is great. It would be great to pull out the things that would be listed in communications about the workshop that clarify what participants will learn. Those might take the form of items that complete the sentence: "After the workshop you will know how to..."

- catalog learning objectives
  - get catalog entry in to spreadsheet (database?) (include variables in catalog??) | minimum required ...
  - search catalog and add specific variables to ETL process
  - share metadata with other research groups?
