### ISSUE TITLE
Define OHDSI symposium workshop learning objectives for Geocoding

### ISSUE THREAD

**Issue by kzollove** [OHDSI/GIS#352]

**Comment by tibbben** [comment]
- geocoders learning objectives
  - preprocessing issues (address normalization, one string vs pieces, abbreviations, missing data)
    - takehome: careful planning in the collection of address information will make your life much easier
  - privacy concerns (range of restrictions that seem to be institution dependent)
    - takehome: what is a hipaa compliant geocoder (some sort of chart)
    - takehome: find my iorganizations policy on this
  - choose and configure geocoder -> nominatim (note long install time and not out of the box on docker/kubernetes)
    - options: 
      - https://medium.com/@geocodio/compare-hipaa-compliant-geocoding-providers-dd0faa161b6f
      - https://www.linkedin.com/pulse/comparing-hipaa-compliant-geocoding-services-michele-hansen/
    - takehome: nominatim for international, be careful with address normalization and multiple results
    - takehome: degauss for North America, if you are more adventurous PostGIS + Tiger
    - takehome: if you have money, pay for a good service (ESRI enterprise, geocodio, ...)
    - takehome: not as easy as it looks (long installs, medium sized data @ 10s of GBs)
  - [ run batch ] and interpret results (match scores, multiple matches, how to account for errors)
