### ISSUE TITLE
[2024 Symposium] Background and Introduction

### ISSUE THREAD

**Issue by kzollove** [OHDSI/GIS#357]
Slides due the 11th

How this ties into OHDSI (Andrew has this covered from ESIP presentation)

Tim will present 4-5 slides introducing GIS generally

**Comment by tibbben** [comment]
Potential materials:
- [GIS cheatsheet](https://github.com/DataCurationNetwork/curation-curriculum/blob/fe797209e53cb41c75330e0e9d9d06f3cb47fec5/Specialized%20Data%20Types/Geospatial/Exercise%20Materials/1_3_GIS_Cheat_Sheet.pdf)

**Comment by kzollove** [comment]
We want a fairly short intro to "what is GIS?" - ~10 min max

What kinds of things need to be addressed? How to start implementing and using them
