### ISSUE TITLE
Rename feature_index to variable_source

### ISSUE THREAD

**Issue by kzollove** [OHDSI/GIS#68]
The name feature_index is confusing as "feature" means something different in the context of this project than in the wider GIS community. Instead of the term "feature", we will use the term "variable" which is functionally equivalent in the context of the project. Further, we will address the fact that this table is not exactly an index, but more like a second source table due to the amount of unique data it contains.

Changes should be made in the SQL db and in the R code that touches the SQL db.

**Comment by kzollove** [comment]
In SQL this change entails:
- Changing table name from feature_index to variable_source
- Changing column names that use "feature" or feature_index" to "variable" or "variable_source"

**Comment by kzollove** [comment]
Pretty much right as I was finishing this it hit me that this should be called **variable_registry**

@rtmill thoughts? Worth changing again?

**Comment by rtmill** [comment]
@kzollove If you feel strongly enough about it being a better fit to give you the motivation to make the change, the name makes sense to me.
